name : update data with github action.


on:
  push:
    tags:
      - 'v*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Deno script
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.x'

      - name: Get variables
        id: ref
        run: Output="GITHUB=$GITHUB_REF"

      - name: check value of output
        run: echo value of output is $Output


      - name: Run Deno script
        run: deno run --allow-read --allow-run --allow-write --allow-env .github/scripts/update_readme.ts
        env:
          VERSION: $Output

