name : update data with github action.


on:
  push:
    tags:
      - 'v*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Deno script
        uses: denoland/setup-deno@v1
        with:
          deno-version: '1.x'

      - name: get working directory
        run: ls -a -l 


      - name: Extract version tag
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Run Deno script
        run: deno run --allow-read --allow-write --allow-env .github/scripts/update_readme.ts
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          OUTPUT: $GITHUB_OUTPUT

